- name: Ensure unzip is installed
  apt:
    name: unzip
    state: present
    update_cache: yes

- name: Download Terraform zip
  get_url:
    url: https://releases.hashicorp.com/terraform/1.8.4/terraform_1.8.4_linux_amd64.zip
    dest: /tmp/terraform.zip

- name: Unzip Terraform
  unarchive:
    src: /tmp/terraform.zip
    dest: /usr/local/bin/
    remote_src: yes

- name: Make sure terraform is executable
  file:
    path: /usr/local/bin/terraform
    mode: '0755'

- name: Add Terraform to PATH
  lineinfile:
    path: /etc/profile.d/terraform.sh
    line: 'export PATH=$PATH:/usr/local/bin'
    create: yes

