- name: Download Vault zip
  get_url:
    url: https://releases.hashicorp.com/vault/1.17.0/vault_1.17.0_linux_amd64.zip
    dest: /tmp/vault.zip

- name: Unzip Vault
  unarchive:
    src: /tmp/vault.zip
    dest: /usr/local/bin/
    remote_src: yes

- name: Make sure vault is executable
  file:
    path: /usr/local/bin/vault
    mode: '0755'

- name: Add Vault to PATH
  lineinfile:
    path: /etc/profile.d/vault.sh
    line: 'export PATH=$PATH:/usr/local/bin'
    create: yes

